insert into WSFCONFIG (name, type, value) values ('minEarnPercent_Select_CheckPoint','String','8.0');
insert into WSFCONFIG (name, type, value) values ('do_History_Analyze_In_Daily_Selection','String','false');
insert into WSFCONFIG (name, type, value) values ('nextDatePriceIncPercent','String','1.10');
insert into WSFCONFIG (name, type, value) values ('insert_length_mock_price_count_indicator','String','120');
insert into WSFCONFIG (name, type, value) values ('analyse.select.stock.list','String','sh601318,sh600547,sz002797');
insert into WSFCONFIG (name, type, value) values ('realtime.display.stock.list','String','sh000001,sz399001,sz399006');
insert into WSFCONFIG (name, type, value) values ('general_CheckPoint','String','Trend_PhaseI_GuanCha;Trend_PhaseII_JianCang;Trend_PhaseIII_ChiGu;Trend_PhaseVI_JianCang;QSDD_Top_Area;QSDD_Bottom_Area;QSDD_Bottom_Gordon;LuZao_GordonO_MA43_DownCross_MA86;LuZao_GordonI_MA19_UpCross_MA43;LuZao_GordonII_MA19_UpCross_MA86;LuZao_DeadIII_MA43_DownCross_MA86;LuZao_DeadI_MA43_UpCross_MA86;LuZao_DeadII_MA19_DownCross_MA43;ShenXian_Gordon;ShenXian_Dead;MACD_Gordon;MACD_Dead;WR_Top_Area;WR_Bottom_Area;WR_Bottom_Gordon;High_Price_Digit_In_Order;Low_Price_Digit_In_Order;WR_DI_BeiLi;MAGIC_NIGHT_DAYS_SHANG_ZHANG;MAGIC_NIGHT_DAYS_XIA_DIE;AiTrend_Top_Area;AiTrend_Bottom_Area;aiTrendBottomCrossType;');
insert into WSFCONFIG (name, type, value) values ('specify_Select_CheckPoint','String','LuZao_PhaseII_MACD_WEEK_GORDON_MACD_DAY_DIF_CROSS_0;LuZao_PhaseIII_MACD_WEEK_GORDON_MACD_DAY_DIF_CROSS_0;LuZao_PhaseII_MACD_WEEK_GORDON_KDJ_WEEK_GORDON;LuZao_PhaseIII_MACD_WEEK_GORDON_KDJ_WEEK_GORDON;MACD_TWICE_GORDON_W_Botton_MACD_DI_BEILI;MACD_TWICE_GORDON_W_Botton_TiaoKong_ZhanShang_Bull;LuZao_KDJ_Gordon_TiaoKongGaoKai;AiTrend_Top_Area;AiTrend_Bottom_Area;aiTrendBottomCrossType;');
insert into WSFCONFIG (name, type, value) values ('zone','String','aliyun');
insert into WSFCONFIG (name, type, value) values ('report.estimate.html.file','String','/home/eyaweiw/easystogu/report/estimate_nextDate.html');
insert into WSFCONFIG (name, type, value) values ('report.analyse.html.file','String','/home/eyaweiw/easystogu/report/report_currentDate.html');
insert into WSFCONFIG (name, type, value) values ('report.estimate.both.html.file','String','/home/eyaweiw/easystogu/report/estimate_both_currentDate.html');
insert into WSFCONFIG (name, type, value) values ('report.recent.analyse.html.file','String','/home/eyaweiw/easystogu/report/report_recent_currentDate.html');
insert into WSFCONFIG (name, type, value) values ('yahoo.csv.file.path','String','/home/eyaweiw/easystogu/CSVData1/');
insert into WSFCONFIG (name, type, value) values ('sina.history.file.path','String','/home/eyaweiw/easystogu/SinaHistoryData/');
insert into WSFCONFIG (name, type, value) values ('trendmode.json.file.path','String','/home/eyaweiw/github/EasyStoGu/Portal/src/main/resources/TrendMode/');
insert into WSFCONFIG (name, type, value) values ('stockPrice.import_export.file.path','String','/home/eyaweiw/github/EasyStoGu/CommonLib/src/main/resources/stockPrice/');
insert into WSFCONFIG (name, type, value) values ('DailyUpdateStockPriceByBatch','String','True');
insert into WSFCONFIG (name, type, value) values ('Access-Control-Allow-Origin','String','*');
insert into WSFCONFIG (name, type, value) values ('cixin_Stock_Length','Int   ','172');
insert into WSFCONFIG (name, type, value) values ('indicatorDBType','String','SQL');
insert into WSFCONFIG (name, type, value) values ('real_Time_Get_ZiJin_Liu_PageNumber','String','10');

insert into favorites_stock (stockid,userid) values (300333,'admin');
insert into favorites_stock (stockid,userid) values (300311,'admin');
insert into favorites_stock (stockid,userid) values (600036,'admin');
insert into favorites_stock (stockid,userid) values (600547,'admin');
insert into favorites_stock (stockid,userid) values (002797,'admin');
insert into favorites_stock (stockid,userid) values (601066,'admin');
insert into favorites_stock (stockid,userid) values (600030,'admin');
insert into favorites_stock (stockid,userid) values (300676,'admin');
insert into favorites_stock (stockid,userid) values (300760,'admin');
insert into favorites_stock (stockid,userid) values (002415,'admin');
insert into favorites_stock (stockid,userid) values (600837,'admin');
insert into favorites_stock (stockid,userid) values (601318,'admin');
insert into favorites_stock (stockid,userid) values (600519,'admin');
insert into favorites_stock (stockid,userid) values (000002,'admin');
insert into favorites_stock (stockid,userid) values (002673,'admin');
insert into favorites_stock (stockid,userid) values (300688,'admin');
insert into favorites_stock (stockid,userid) values (300033,'admin');
insert into favorites_stock (stockid,userid) values (300059,'admin');
insert into favorites_stock (stockid,userid) values (600585,'admin');
insert into favorites_stock (stockid,userid) values (601519,'admin');
insert into favorites_stock (stockid,userid) values (002352,'admin');
insert into favorites_stock (stockid,userid) values (600276,'admin');
insert into favorites_stock (stockid,userid) values (002594,'admin');
insert into favorites_stock (stockid,userid) values (603999,'admin');
