version: '3.4'

networks:
  easystogu_network:
    driver: bridge

services:
  cassandra:
    image: eyaweiw.cn:5000/bitnami/cassandra:4.0.0
    hostname: cassandra.easystogu.cn
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra/init-scripts:/docker-entrypoint-initdb.d
      - /mnt/5a538d29-2608-4ba0-985a-0f143703ef5c/cassandra/data:/bitnami/cassandra/data
    networks:
      - easystogu_network
    restart: always
